#!/bin/bash
pushd bin
jar cvfm marvin.jar MANIFEST.MF org/
popd

ssh $1 'if [ ! -d /usr/share/marvin ] ; then mkdir /usr/share/marvin; fi'
ssh $1 'if [ ! -d /usr/share/marvin/bin ] ; then mkdir /usr/share/marvin/bin; fi'
ssh $1 'if [ ! -d /usr/share/marvin/lib ] ; then mkdir /usr/share/marvin/lib; fi'

#marvin
scp -r bin/marvin.jar $1:/usr/share/marvin/bin/

#neo4j
scp -r lib/* $1:/usr/share/marvin/lib

ssh $1 '/etc/init.d/marvin restart'

