#!/bin/bash

DEST="root@192.168.0.100"
if [ ! -z "$1" ] ; then DEST=$1; fi

pushd bin
jar cvfm marvin.jar MANIFEST.MF org/
popd

ssh $DEST 'if [ ! -d /usr/share/marvin ] ; then mkdir /usr/share/marvin; fi'
ssh $DEST 'if [ ! -d /usr/share/marvin/bin ] ; then mkdir /usr/share/marvin/bin; fi'
ssh $DEST 'if [ ! -d /usr/share/marvin/lib ] ; then mkdir /usr/share/marvin/lib; fi'

#marvin
scp -r bin/marvin.jar $DEST:/usr/share/marvin/bin/

#neo4j
scp -r lib/* $DEST:/usr/share/marvin/lib

ssh $DEST '/etc/init.d/marvin restart'

